server:
  servlet:
    context-path: /societies/
  port: 1996

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xx1602614lpc
    url: jdbc:mysql:///societies_db?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useUnicode=true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    encoding: UTF-8
    suffix: .html
#    prefix: classpath*:/templates/
    cache: false
    check-template-location: true
    mode: HTML
  web:
    resources:
      static-locations: classpath:/static/
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    connect-timeout: 10000

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

mybatis-plus:
  mapper-locations: classpath:/mapping/*Mapper.xml
  type-aliases-package: com.lpc.system1.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: count=countsql